Broadway CHAIN - SANDBOX/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Barking &amp; Dagenham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barnet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bexley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bromley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City of London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croydon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ealing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greenwich</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hackney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hammersmith &amp; Fulham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haringey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harrow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Havering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hillingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hounslow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Islington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kensington &amp; Chelsea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kingston upon Thames</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lambeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lewisham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redbridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Richmond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southwark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sutton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tower Hamlets</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count_of_SSOs__c</fullName>
        <label>Count of SSOs</label>
        <summaryForeignKey>Single_Service_Offer__c.Client__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date_NSNO_offer_made__c</fullName>
        <label>Date offer made</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_outcome__c</fullName>
        <label>Offer Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Team__c</fullName>
        <label>Created by Project/Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Action__c</fullName>
        <label>Single Service Offer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team_making_single_service_offer__c</fullName>
        <label>Team making single service offer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/objects/NSNO_Event__c.object
<CustomObject>
    <description>Use for recording NSNO container event, related to which are NSNO stay timeline events</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NSNO Events</relationshipLabel>
        <relationshipName>NSNO_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Count_of_SSOs__c</fullName>
        <label>Count of SSOs</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rough_sleeping_status__c</fullName>
        <label>Rough sleeping status</label>
        <picklist>
            <picklistValues>
                <fullName>New rough sleeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Known rough sleeper with no SSO/local connection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Known rough sleeper with SSO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NSNO Event</label>
    <nameField>
        <displayFormat>NSNO-{00000}</displayFormat>
        <label>NSNO Event ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSNO Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/objects/Single_Service_Offer__c.object
<CustomObject>
    <description>Used to create Single Service Offers (SSOs)</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_offer_made__c</fullName>
        <label>Date offer made</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NSNO_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NSNO Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Client__c</field>
                <operation>equals</operation>
                <valueField>NSNO_Event__c.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NSNO_Event__c</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Outcome__c</fullName>
        <label>Offer Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Single_Service_Offer__c</fullName>
        <label>Single Service Offer</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team_making_SSO__c</fullName>
        <label>Team making SSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeline_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Relate this SSO to an NSNO or NLOS referral</inlineHelpText>
        <label>NSNO/NLOS Stay Event</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5</booleanFilter>
            <filterItems>
                <field>Timeline_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>NSNO Referrals, NLOS Referrals</value>
            </filterItems>
            <filterItems>
                <field>$Source.Client__c</field>
                <operation>equals</operation>
                <valueField>Timeline_Event__c.Client__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Default_Project_Name__c</field>
                <operation>equals</operation>
                <valueField>Timeline_Event__c.Accommodation2__c</valueField>
            </filterItems>
            <filterItems>
                <field>Timeline_Event__c.Arrival_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Timeline_Event__c.Reason_offer_not_made__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Timeline_Event__c</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Single Service Offer</label>
    <nameField>
        <displayFormat>SSO-{00000}</displayFormat>
        <label>Single Service Offer ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Single Service Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/classes/SingleServiceOfferTriggerHelperTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true) 
private class SingleServiceOfferTriggerHelperTest {

    static testMethod void unitTest() {

       Campaign c = new Campaign(
            Name = 'Assessment Hub', Borough__c = 'Barnet'
        );
        insert c;
        
        User usr = new User(
            Username = 'cstm@cstm.dl', Email = 'cstm@cstm.dl', Department = 'Department', Division = 'Division',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id, FirstName = 'Joe',
            LastName = 'Bloggs', Alias = 'jblo', TimeZoneSidKey = 'Europe/Dublin', LocaleSidKey = 'en_IE',
            EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', Default_Project_Id__c = c.Id
        );
        insert usr;

        System.runAs(usr) {
                
    
            Account Client = new Account(LastName = 'Nexus451', RecordType = new RecordType( Name = 'Client Account' ), Project_Team__pc = 'NLOS Assessment Hub');
            insert Client;
            
            Client = [SELECT Id, PersonContactId FROM Account WHERE Id = :Client.Id];
            
            NSNO_Event__c NSNOEvent = new NSNO_Event__c(Client__c = Client.PersonContactId, Rough_sleeping_status__c = 'New rough sleeper');
            insert NSNOEvent;
                
            Contact contact = [SELECT Id,  Special_Action__c, Date_NSNO_offer_made__c, 
                                        Team_making_single_service_offer__c,
                                        Offer_Outcome__c 
                                        FROM contact WHERE Id = :Client.PersonContactId];
               
            DateTime Now = DateTime.now();
            
            id NLOSRecordTypeID = Schema.SObjectType.Timeline_Event__c.RecordTypeInfosByName.get('NLOS Referrals').RecordTypeId; 
            
            Timeline_Event__c TimelineEvent1 = new Timeline_Event__c(
                Client__c = Client.PersonContactId,
                Event__c = 'Accommodation Stay',
                Creating_User_Organisation__c = 'CSTM',
                Date__c = Now,
                Project_Team__c = usr.Default_Project_Id__c,
                Borough_Street_Site__c = 'Test Timeline Event',
                RecordTypeId = NLOSRecordTypeID,
                Accommodation__c = c.Id,
                Arrival_Date__c = system.today(),
                NLOS_Hub_Room_Number__c = 'Test1',
                Reason_brought_to_NLOS__c = 'For further assessment',
                Direct_transfer_to_NLOS_accommodation__c = 'Yes'                
            );
            insert TimelineEvent1;          
                
            TimelineEvent1 = [SELECT Id, Ward__c FROM Timeline_Event__c WHERE Id = :TimelineEvent1.Id];
    
                       
           Timeline_Event__c TimelineEvent2 = new Timeline_Event__c(
                Client__c = Client.PersonContactId,
                Event__c = 'Accommodation Stay',
                Creating_User_Organisation__c = 'CSTM',
                Date__c = Now,
                Project_Team__c = usr.Default_Project_Id__c,
                Borough_Street_Site__c = 'Test Timeline Event',
                RecordTypeId = NLOSRecordTypeID,
                Accommodation__c = c.Id,
                Arrival_Date__c = system.today(),
                NLOS_Hub_Room_Number__c = 'Test2',
                Reason_brought_to_NLOS__c = 'For further assessment',
                Direct_transfer_to_NLOS_accommodation__c = 'Yes'    
                
            );
            insert TimelineEvent2;
    
            //create Single Service Offer
            
            Single_Service_Offer__c sso1 = new Single_Service_Offer__c(Date_offer_made__c = system.today(),
                                                                        Team_making_SSO__c = 'Team for Test 1',
                                                                        Single_Service_Offer__c = 'The first Test',
                                                                        Offer_outcome__c = 'Accepted', 
                                                                        Timeline_Event__c = TimelineEvent1.Id,
                                                                        Client__c = Client.PersonContactId,
                                                                        NSNO_Event__c = NSNOEvent.Id);
            test.startTest();
                insert sso1;
            
                contact = [SELECT Id, Special_Action__c, Date_NSNO_offer_made__c, 
                                        Team_making_single_service_offer__c,
                                        Offer_Outcome__c 
                                        FROM contact WHERE Id = :Client.PersonContactId];           
                
                NSNOEvent = [select Count_of_SSOs__c from NSNO_Event__c where Id = :NSNOEvent.Id];
                system.assertEquals(NSNOEvent.Count_of_SSOs__c, 1);
                
                system.assertEquals(contact.Special_Action__c, sso1.Single_Service_Offer__c);
                system.assertEquals(contact.Team_making_single_service_offer__c, sso1.Team_making_SSO__c);
                system.assertEquals(contact.Offer_Outcome__c, sso1.Offer_outcome__c);
              
                
                // insert another SSO and check Contact values updated to most recent record values
    
                Single_Service_Offer__c sso2 = new Single_Service_Offer__c(Date_offer_made__c = system.today(),
                                                                        Team_making_SSO__c = 'Team for Test 2',
                                                                        Single_Service_Offer__c = 'The second Test',
                                                                        Offer_outcome__c = 'Rejected', 
                                                                        Timeline_Event__c = TimelineEvent1.Id,
                                                                        Client__c = Client.PersonContactId,
                                                                        NSNO_Event__c = NSNOEvent.Id);    
                insert sso2;
                
                contact = [SELECT Id, Special_Action__c, Date_NSNO_offer_made__c, 
                            Team_making_single_service_offer__c,
                            Offer_Outcome__c 
                            FROM contact WHERE Id = :Client.PersonContactId];           
                
                NSNOEvent = [select Count_of_SSOs__c from NSNO_Event__c where Id = :NSNOEvent.Id];
                system.assertEquals(NSNOEvent.Count_of_SSOs__c, 2);
                
                system.assertEquals(contact.Special_Action__c, sso2.Single_Service_Offer__c);
                system.assertEquals(contact.Team_making_single_service_offer__c, sso2.Team_making_SSO__c);
                system.assertEquals(contact.Offer_Outcome__c, sso2.Offer_outcome__c);
                     
                
                // Check SSO Counter on Timeline event
                TimelineEvent1 = [SELECT Id, SSO_Count__c FROM Timeline_Event__c WHERE Id = :TimelineEvent1.Id];
                system.assertEquals(2, TimelineEvent1.SSO_Count__c);
                
                // update timeline on SSO and recheck counter
                sso2 = [select Timeline_Event__c from Single_Service_Offer__c where Id =:sso2.Id];
                sso2.Timeline_Event__c = TimelineEvent2.Id;
                update sso2;
                
                TimelineEvent1 = [SELECT Id, SSO_Count__c FROM Timeline_Event__c WHERE Id = :TimelineEvent1.Id];
                system.assertEquals(1, TimelineEvent1.SSO_Count__c);
                            
                // delete sso's and check client values are blanked out
                list<Single_Service_Offer__c> ssoList = [select id from Single_Service_Offer__c where Client__c = :contact.Id];                                                             
                delete ssoList;
    
                contact = [SELECT Id, Special_Action__c, Date_NSNO_offer_made__c, 
                            Team_making_single_service_offer__c,
                            Offer_Outcome__c
                            FROM contact WHERE Id = :Client.PersonContactId];   
                                        
                system.assert(string.isBlank(contact.Special_Action__c));
                system.assert(string.isBlank(contact.Team_making_single_service_offer__c));
                system.assert(string.isBlank(contact.Offer_Outcome__c));
                          
    
                // Check SSO Counter on Timeline event
                TimelineEvent1 = [SELECT Id, SSO_Count__c FROM Timeline_Event__c WHERE Id = :TimelineEvent1.Id];
                system.assertEquals(0, TimelineEvent1.SSO_Count__c);
                
                // run batch class method for coverage
                string soql = 'select Id, SSO_Count__c from Timeline_event__c where Id= ' + '\'' + TimelineEvent1.Id + '\'';
                SingleServiceOfferBatchProcess ssoBatch = new SingleServiceOfferBatchProcess(soql);
                Database.executeBatch(ssoBatch);
                
            test.stopTest();
        
        }
        
    }
    

    
    
}