Broadway CHAIN - SANDBOX/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Count_of_SSOs__c</fullName>
        <label>Count of SSOs</label>
        <summaryForeignKey>Single_Service_Offer__c.Client__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date_NSNO_offer_made__c</fullName>
        <label>Date offer made</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_outcome__c</fullName>
        <label>Offer Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Special_Action__c</fullName>
        <label>Single Service Offer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team_making_single_service_offer__c</fullName>
        <label>Team making single service offer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/objects/NSNO_Event__c.object
<CustomObject>
    <description>Use for recording NSNO container event, related to which are NSNO stay timeline events</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NSNO Events</relationshipLabel>
        <relationshipName>NSNO_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Count_of_SSOs__c</fullName>
        <label>Count of SSOs</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NSNO Event</label>
    <nameField>
        <displayFormat>NSNO-{00000}</displayFormat>
        <label>NSNO Event ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSNO Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/objects/Single_Service_Offer__c.object
<CustomObject>
    <description>Used to create Single Service Offers (SSOs)</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_offer_made__c</fullName>
        <label>Date offer made</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NSNO_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NSNO Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Client__c</field>
                <operation>equals</operation>
                <valueField>NSNO_Event__c.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NSNO_Event__c</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Outcome__c</fullName>
        <label>Offer Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Single_Service_Offer__c</fullName>
        <label>Single Service Offer</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team_making_SSO__c</fullName>
        <label>Team making SSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeline_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Relate this SSO to an NSNO or NLOS referral</inlineHelpText>
        <label>NSNO/NLOS Stay Event</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5</booleanFilter>
            <filterItems>
                <field>Timeline_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>NSNO Referrals, NLOS Referrals</value>
            </filterItems>
            <filterItems>
                <field>$Source.Client__c</field>
                <operation>equals</operation>
                <valueField>Timeline_Event__c.Client__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.Default_Project_Name__c</field>
                <operation>equals</operation>
                <valueField>Timeline_Event__c.Accommodation2__c</valueField>
            </filterItems>
            <filterItems>
                <field>Timeline_Event__c.Arrival_Date__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Timeline_Event__c.Reason_offer_not_made__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Timeline_Event__c</referenceTo>
        <relationshipLabel>Single Service Offers</relationshipLabel>
        <relationshipName>Single_Service_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Single Service Offer</label>
    <nameField>
        <displayFormat>SSO-{00000}</displayFormat>
        <label>Single Service Offer ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Single Service Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Broadway CHAIN - SANDBOX/src/classes/SingleServiceOfferTriggerHelper.cls
public with sharing class SingleServiceOfferTriggerHelper {

    // Updates Single Service Offer (SSO) related fields on the parent client record with equivalent fields
    // of the most recently created Single Service Offer record
    public static void updateContact (map<Id, Single_Service_Offer__c> ssoMap){
        
        try{
            // extract list of clients related to updated/inserted SSO records 
            list<Single_Service_Offer__c> ssoList = [select Client__r.Id from Single_Service_Offer__c where id in:ssoMap.keySet() ALL ROWS];
            
            set<string> clientIdList = new set <string>();
            
            // populate client id list
            for (Single_Service_Offer__c sso :ssoList){
                clientIdList.add(sso.Client__r.Id);
            }
            
            if (!clientIdList.isEmpty()){
                // extract client SSO fields and the most recently created SSO record related to the client
                list<Contact> contactList = [select Id, Special_Action__c, Date_NSNO_offer_made__c, Team_making_single_service_offer__c,
                                                Offer_Outcome__c,
                                                (select Date_offer_made__c, Team_making_SSO__c,Single_Service_Offer__c,
                                                            Offer_outcome__c, Timeline_Event__c
                                                            from Single_Service_Offers__r order by Date_offer_made__c desc, Id desc LIMIT 1)
                                                from contact where id in :clientIdList];

                for (contact c :contactList){                   
                    if (c.Single_Service_Offers__r.isEmpty()){ // blank out values if no SSO's exist
                        c.Special_Action__c = '';
                        c.Date_NSNO_offer_made__c = null;
                        c.Team_making_single_service_offer__c = ''; 
                        c.Offer_Outcome__c = '';                                                                     
                    } else {
                        // stamp client fields with field values from SSO record
                        c.Special_Action__c = c.Single_Service_Offers__r[0].Single_Service_Offer__c;
                        c.Date_NSNO_offer_made__c = c.Single_Service_Offers__r[0].Date_offer_made__c;
                        c.Team_making_single_service_offer__c = c.Single_Service_Offers__r[0].Team_making_SSO__c; 
                        c.Offer_Outcome__c = c.Single_Service_Offers__r[0].Offer_outcome__c;
                           }
                }
                
                update contactList;
            }   
            
            
            
        } catch (exception e){
            
            system.debug('ERROR...  ' + e.getMessage() + ' : ' + e.getStackTraceString());              
        }   
        
        
        
        
    }


    // Updates count of related Single Service Offer (SSO) held on associated Timeline Event record
    public static void updateTimelineCounter (map<Id, Single_Service_Offer__c> ssoMap){
        
        try{
            // extract list of clients related to updated/inserted SSO records 
            list<Single_Service_Offer__c> ssoList = [select Timeline_Event__c from Single_Service_Offer__c where id in:ssoMap.keySet() ALL ROWS];
            
            set<Id> timelineIdList = new set <Id>();
            
            // populate timeline event id list
            for (Single_Service_Offer__c sso :ssoList){
                timelineIdList.add(sso.Timeline_Event__c);
            }
            
            updateSSOTimelineCounter(timelineIdList, null);
            
        } catch (exception e){
            
            system.debug('ERROR...  ' + e.getMessage() + ' : ' + e.getStackTraceString());              
        }   
        
        
    }
    
    public static void updateSSOTimelineCounter(set<Id> timelineIdList, map<Id, Timeline_Event__c> timelineEventList){

        
        if (!timelineIdList.isEmpty()){
            
            if (timelineEventList  == null) {
                // extract SSO Count field from timeline event records
                timelineEventList = new map<Id, Timeline_Event__c>([select Id, SSO_Count__c 
                                                                    from Timeline_Event__c 
                                                                    where id in :timelineIdList]);
            }
                                                                                                      
            map<Id, boolean> timelineUpdated = new map<Id, boolean>();
            for (Id tId :timelineEventList.keySet()){
                timelineUpdated.put(tId, false);
            }
            
            List <AggregateResult> SSOs = new List<AggregateResult>();
            // get current record counts    
            SSOs = [Select Timeline_Event__c, Count(Id) recCount 
                        From Single_Service_Offer__c Where Timeline_Event__c in: timelineIdList
                        group by Timeline_Event__c];            
            
            // update timeline event records
            for(AggregateResult ar: SSOs){
                if (string.isnotBlank(string.valueOf(ar.get('Timeline_Event__c')))){              
                    timelineEventList.get((string.valueOf(ar.get('Timeline_Event__c')))).SSO_Count__c = Decimal.ValueOf(String.ValueOf(ar.get('recCount'))); 
                    timelineUpdated.put(string.valueOf(ar.get('Timeline_Event__c')), true);
                }
            } 
            
            // set count to 0 if no SSO's exist                             
            for (Id tId :timelineEventList.keySet()){
                if (timelineUpdated.get(tId) == false){
                    timelineEventList.get(tId).SSO_Count__c = 0;
                }
            }
            
                
            update timelineEventList.values();
        }           
        
    }
    
    // Utility method to update all SSO Counter fields on all Timeline event records
    
    public static void updateAllSSOCounters(list<Timeline_Event__c>timelineEventList){

        try{        
            set<Id> timelineIdList = new set<Id>();
            if (!timelineEventList.isEmpty()){
                Map<Id, Timeline_Event__c> timelineMap = new Map<Id, Timeline_Event__c>(timelineEventList);
                timelineIdList  = timelineMap.keySet();
                updateSSOTimelineCounter(timelineIdList, timelineMap);
            }

        } catch (exception e){
            
            system.debug('ERROR...  ' + e.getMessage() + ' : ' + e.getStackTraceString());              
        }       
    
    }

    // Triggered from SSO changes 
    // to update the SSO count value held 
    // on the associated NSNO Event object 
    public static void updateNSNOEvents( set<Id> SSOIds, set<Id> NSNOEventIds){
        
        set<Id> NSNOEventIdList = new set<Id>();
        if (!NSNOEventIds.isEmpty()){
            NSNOEventIdList.addAll(NSNOEventIds);
        }
        list<Single_Service_Offer__c> SSOs = new list<Single_Service_Offer__c>();        
system.debug(' @@@@@@@@@@@@  SSOIDs   ' + SSOIds);      
        try{
            if (!SSOIds.isEmpty()){
                SSOs = [Select NSNO_Event__c from Single_Service_Offer__c 
                                        where Id in :SSOIds ALL ROWS];    
                
                if(!SSOs.isEmpty()){
                    for(Single_Service_Offer__c SSO :SSOs){
                        if (string.isnotBlank(SSO.NSNO_Event__c)){
                            NSNOEventIdList.add(SSO.NSNO_Event__c);
                        }
                    }

                }
            }
system.debug(' @@@@@@@@@@@@  NSNOEventIdList   ' + NSNOEventIdList);                
            if (!NSNOEventIdList.isEmpty()){
                
                map<Id, NSNO_Event__c> NSNOEventsMap = new map<Id, NSNO_Event__c>([select Count_of_SSOs__c
                                                                                    from NSNO_Event__c where id in :NSNOEventIdList]);
                
                AggregateResult [] allSSOs = [select NSNO_Event__c nsnoId, count (Id) RecordCount 
                                    From Single_Service_Offer__c  where
                                    NSNO_Event__c in :NSNOEventIdList
                                    Group By NSNO_Event__c];
                if (!allSSOs.isEmpty()){
                    for (AggregateResult ar :allSSOs){
                        string recId = string.valueOf(ar.get('nsnoId'));
                        integer recCount = integer.valueOf(ar.get('RecordCount'));
                        NSNOEventsMap.get(recId).Count_of_SSOs__c = recCount;
                    }
                } else {
                    for (NSNO_Event__c nsno :NSNOEventsMap.values())
                    {            
                        nsno.Count_of_SSOs__c = 0;                      
                    }                
                 
                }               
                
                update NSNOEventsMap.values();
            }
        
        } catch (exception e){
            
            system.debug('ERROR...  ' + e.getMessage() + ' : ' + e.getStackTraceString());   
        }
    
    }
    
    
}